/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.copadomundo;

/**
 *
 * @author dell
 */
public class Usuáriocomum extends javax.swing.JFrame {

    /**
     * Creates new form Usuáriocomum
     */
    public Usuáriocomum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GA = new javax.swing.JToggleButton();
        GB = new javax.swing.JToggleButton();
        GC = new javax.swing.JToggleButton();
        GD = new javax.swing.JToggleButton();
        GE = new javax.swing.JToggleButton();
        GF = new javax.swing.JToggleButton();
        GG = new javax.swing.JToggleButton();
        GH = new javax.swing.JToggleButton();
        Grupos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        GA.setSelected(true);
        GA.setText("Grupo A");
        getContentPane().add(GA);
        GA.setBounds(160, 100, 90, 22);

        GB.setSelected(true);
        GB.setText("Grupo B");
        getContentPane().add(GB);
        GB.setBounds(160, 130, 90, 22);

        GC.setSelected(true);
        GC.setText("Grupo C");
        getContentPane().add(GC);
        GC.setBounds(160, 160, 90, 22);

        GD.setSelected(true);
        GD.setText("Grupo D");
        getContentPane().add(GD);
        GD.setBounds(160, 190, 90, 22);

        GE.setSelected(true);
        GE.setText("Grupo E");
        getContentPane().add(GE);
        GE.setBounds(160, 220, 90, 22);

        GF.setSelected(true);
        GF.setText("Grupo F");
        getContentPane().add(GF);
        GF.setBounds(160, 250, 90, 22);

        GG.setSelected(true);
        GG.setText("Grupo G");
        getContentPane().add(GG);
        GG.setBounds(160, 280, 90, 22);

        GH.setSelected(true);
        GH.setText("Grupo H");
        getContentPane().add(GH);
        GH.setBounds(160, 310, 90, 22);

        Grupos.setText("Grupos da copa");
        Grupos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        Grupos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Grupos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Grupos.setOpaque(true);
        getContentPane().add(Grupos);
        Grupos.setBounds(160, 70, 90, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CDM.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-340, 0, 770, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuáriocomum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuáriocomum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuáriocomum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuáriocomum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuáriocomum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GA;
    private javax.swing.JToggleButton GB;
    private javax.swing.JToggleButton GC;
    private javax.swing.JToggleButton GD;
    private javax.swing.JToggleButton GE;
    private javax.swing.JToggleButton GF;
    private javax.swing.JToggleButton GG;
    private javax.swing.JToggleButton GH;
    private javax.swing.JLabel Grupos;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
